server:
  port: 8080
  servlet.encoding:
    charset: UTF-8
    force: true
spring:
  servlet.multipart:
    max-file-size: 50MB
    max-request-size: 50MB
  #  sql.init.mode: always
  datasource:
    url: jdbc:h2:file:./test-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    #    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    #    hibernate.ddl-auto: update
    #    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false